version: 2

defaults: &defaults
    working_directory: '~/project'
    docker:
        - image: 'docker:17.05.0-ce-git'

attach_workspace: &attach_workspace
    attach_workspace:
        at: '.'

persist_workspace: &persist_workspace
    persist_to_workspace:
        root: '.'
        paths: [ '.' ]

fan_in: &fan_in
    <<: *defaults
    steps: [ { run: 'whoami' } ]

build_image: &build_image
    <<: *defaults
    steps:
        - *attach_workspace
        - setup_remote_docker
        - run: 'docker login -u $DOCKER_USER -p $DOCKER_PASS'
        - run:
            name: 'Build docker image'
            command: |
                cd "${DOCKER_PATH}" && \
                docker build -t "${DOCKER_TAG}" .
        - run:
            name: 'Push docker image'
            command: |
                docker push "${DOCKER_TAG}"

workflows:
    version: 2
    pipeline:
        jobs:
            - fetch_code:
                filters:
                    branches: { only: master }

            - build_2x:
                requires: [ fetch_code ]
            - build_3x_frontend:
                requires: [ fetch_code ]
            - build_3x_frontend_web:
                requires: [ fetch_code ]
            - build_3x_frontend_ci:
                requires: [ fetch_code ]

            - fan_in_1:
                requires:
                    - build_2x
                    - build_3x_frontend
                    - build_3x_frontend_web
                    - build_3x_frontend_ci

jobs:

    fetch_code:
        <<: *defaults
        steps:
            - checkout
            - *persist_workspace

    build_2x:
        <<: *build_image
        environment:
          - DOCKER_PATH: './2x'
          - DOCKER_TAG: 'halplatform/php:2x'

    build_3x_frontend:
        <<: *build_image
        environment:
          - DOCKER_PATH: './frontend'
          - DOCKER_TAG: 'halplatform/php:frontend'

    build_3x_frontend_web:
        <<: *build_image
        environment:
          - DOCKER_PATH: './frontend-web'
          - DOCKER_TAG: 'halplatform/php:frontend-web'

    build_3x_frontend_ci:
        <<: *build_image
        environment:
          - DOCKER_PATH: './frontend-ci'
          - DOCKER_TAG: 'halplatform/php:frontend-ci'

    fan_in_1:
        <<: *fan_in
