version: 2.1

orbs:
  docker: circleci/docker@0.5.20

filter__master: &filter__master
    filters:
        branches:
            only: [ 'master' ]

workflows:
    version: 2
    pipeline:
        jobs:
            - fetch_code:
                <<: *filter__master

            - build_image:
                name: 'build_ci_73'
                path: './ci-7.3'
                docker-tag: 'ci-7.3'
                requires: [ fetch_code ]

            - build_image:
                name: 'build_ci_80'
                path: './ci-8.0'
                docker-tag: 'ci-8.0'
                requires: [ fetch_code ]

            - fan_in:
                name: 'pipeline-is-finished'
                requires:
                    - build_ci_73
                    - build_ci_80

executors:
  default_executor:
    working_directory: '~/project'
    docker:
      - image: 'circleci/python:3.7'

commands:
    attach_workspace_at_root:
        steps:
            - attach_workspace:
                at: '.'

    persist_to_root_workspace:
        parameters:
            paths:
                type: string
        steps:
            - persist_to_workspace:
                root: '.'
                paths: [ '<< parameters.paths >>' ]

jobs:
    fetch_code:
        executor: default_executor
        steps:
            - checkout
            - persist_to_root_workspace:
                paths: '.'

    fan_in:
        executor: default_executor
        steps: [ { run: 'whoami' } ]

    build_image:
        parameters:
            path:
                type: string
            docker-tag:
                type: string

        executor: default_executor

        steps:
            - attach_workspace_at_root
            - setup_remote_docker
            - docker/check:
                docker-username: DOCKER_USER
                docker-password: DOCKER_PASS
            - docker/build:
                path: '<< parameters.path >>'
                image: 'halplatform/php'
                tag: '<< parameters.docker-tag >>'
            - docker/push:
                image: 'halplatform/php'
                tag: '<< parameters.docker-tag >>'
