version: 2.1

orbs:
  docker: circleci/docker@0.5.20

executors:
  default_executor:
    working_directory: '~/project'
    docker:
      - image: 'circleci/python:3.7'

attach_workspace: &attach_workspace
    attach_workspace:
        at: '.'

persist_workspace: &persist_workspace
    persist_to_workspace:
        root: '.'
        paths: [ '.' ]

fan_in: &fan_in
    executor: default_executor
    steps: [ { run: 'whoami' } ]

build_image: &build_image
    executor: default_executor
    steps:
        - *attach_workspace
        - setup_remote_docker
        - docker/check:
            docker-username: DOCKER_USER
            docker-password: DOCKER_PASS
        - docker/build:
            path: "${DOCKER_PATH}"
            image: "halplatform/php"
            tag: "${DOCKER_TAG}"
        - docker/push:
            image: "halplatform/php"
            tag: "${DOCKER_TAG}"

workflows:
    version: 2
    pipeline:
        jobs:
            - fetch_code:
                filters:
                    branches: { only: master }

            - build_3x_frontend:
                requires: [ fetch_code ]
            - build_3x_frontend_web:
                requires: [ fetch_code ]
            - build_3x_frontend_ci:
                requires: [ fetch_code ]

            - fan_in_1:
                requires:
                    - build_3x_frontend
                    - build_3x_frontend_web
                    - build_3x_frontend_ci

jobs:
    fetch_code:
        executor: default_executor
        steps:
            - checkout
            - *persist_workspace

    build_3x_frontend:
        <<: *build_image
        environment: [ { DOCKER_PATH: './frontend', DOCKER_TAG: 'frontend' } ]

    build_3x_frontend_web:
        <<: *build_image
        environment: [ { DOCKER_PATH: './frontend-web', DOCKER_TAG: 'frontend-web' } ]

    build_3x_frontend_ci:
        <<: *build_image
        environment: [ { DOCKER_PATH: './frontend-ci', DOCKER_TAG: 'frontend-ci' } ]

    fan_in_1:
        <<: *fan_in
